### ISSUE TITLE
We can't use all vue-docgen-api ? and sidebar broken

### ISSUE THREAD

**Issue by flozero** [youngtailors/vue-kawaii#2]
Hello ! First thank's a lot for your work ! :)

I am facing two problems: 
  - when we are using your component it broke every sidebar we make. Maybe i should just add another nav ?

```
sidebar: {
      "/guide/": [
        {
          title: "Guide",
          collapsable: false,
          children: ["", "getting-started", "colors", "borders", "fonts", "filters"]
        },
        {
          title: "Components",
          collapsable: false,
          children: ["components/buttons", "components/modals"]
        }
      ]
    }
```

It seem to break all sidebar navigation because the Home / Components 

- We can't use all vue-docgen-api when i want to use slot comment emit comment and class description maybe it's a choice ?

**Comment by dacsang97** [comment]
You can check repo about [`vuepress-plugin-component-docgen`](https://github.com/youngtailors/vuepress-plugin-component-docgen). This issue belongs to it.
Thank for your reporting.

**Comment by flozero** [comment]
Oh i miss my comment sorry ^ ^

**Comment by dacsang97** [comment]
https://github.com/youngtailors/vuepress-plugin-component-docgen/issues/1
